#!/bin/env bash

# Print the command that would be executed
dry_run=0
# Perform a syntax check on the configuration
test=0
conf_file="$(dirname $0)/dnsmasq.conf"
debug=0
fg=0

while getopts tndf opt; do
  case "${opt}" in
    t)
      test=1 ;;
    n)
      dry_run=1 ;;
    d)
      debug=1 ;;
    f)
      fg=1 ;;
    \?)
      exit 1 ;;
  esac
done
shift $((OPTIND - 1))

declare -a cmd
if ((dry_run)); then
  cmd=(echo)
fi
cmd+=(sudo dnsmasq)

declare -a args=(
  --conf-file="${conf_file}" "$@"
)

if ((test)); then
  args+=(--test)
fi

if ((debug)); then
  args+=(
    --no-daemon
    --dumpfile "${QVM_DIR:-/var/vms}/run/dnsmasq.pcap"
  )
elif ((fg)); then
  args+=("--keep-in-foreground")
else
  args+=(
    --pid-file="${QVM_DIR:-/var/vms}/run/dnsmasq.pid"
  )
fi

"${cmd[@]}" "${args[@]}"
