#!/bin/bash
set -eu

help_msg="
Run a VM from a disk in QVM_DIR/machines.
Optionally enable cloud-init, with seed in QVM_DIR/cloud-init.

Usage: $(basename "$0") [-n] [-u] [-d] [-b] [-i] VM_NAME
"

: "${QVM_DIR:-$(pwd)}"
declare -r QVM_DIR
declare -r MACHINES_DIR="${QVM_DIR}/machines"
declare -r RUNTIME_DIR="${QVM_DIR}/run"

cloud_init=0
dry_run=0
detach=0
user_net=0
first_boot=0
while getopts hnduib opt; do
  case "${opt}" in
    n)
      dry_run=1 ;;
    h)
      echo "${help_msg}"
      exit ;;
    i)
      cloud_init=1 ;;
    d)
      detach=1 ;;
    u)
      user_net=1 ;;
    b)
      first_boot=1 ;;
    *)
      exit 1 ;;
  esac
done
shift $((OPTIND - 1))

declare vm="${1:-}"

if [[ -z "${vm}" ]]; then
  echo "ERROR: required argument: VM_NAME"
  exit 1
fi

drive="${MACHINES_DIR}/${vm}.qcow2"
if ! [[ -f "${drive}" ]]; then
  echo "ERROR: ${drive} not found."
  exit
fi

declare -a cmd args
if ((dry_run)); then
  cmd=(echo)
fi

cmd+=(qemu-system-x86_64)

declare -a args=(
  -name "${vm}"
  -accel kvm
  -cpu host
  -smp 4
  -m 8G
  -drive "file=${drive},format=qcow2,if=virtio"
  -drive "if=pflash,format=raw,readonly=on,file=/usr/share/edk2/ovmf/OVMF_CODE.fd"
  # TODO: Make this more flexible
  -cdrom "${QVM_DIR}/iso/rhel-10.0-x86_64-dvd.iso"
)

# Boot options
# Give us some time to choose boot device
if ((first_boot)); then
  args+=(-boot menu=on,splash-time=5000)
fi

if ((cloud_init)); then
  seed="${QVM_DIR}/localds/${vm}.img"
  if [[ -e "${seed}" ]]; then
    args+=(-drive "file=${seed},if=virtio,format=raw")
  else
    echo "ERROR: Invalid datasource: ${seed}"
    exit 1
  fi
fi

# Networking
declare -A macs=(
  cp "52:54:3b:7b:ca:11"
  wk-1 "52:54:50:67:15:55"
  wk-2 "52:54:0b:a0:c2:15"
)

macaddr() {
  macaddr="${macs[${vm}]:-}"
  if [[ -z "${macaddr:-}" ]]; then
    printf -v macaddr "52:54:%02x:%02x:%02x:%02x" \
           $(( $RANDOM & 0xff)) $(( $RANDOM & 0xff)) \
           $(( $RANDOM & 0xff)) $(( $RANDOM & 0xff))
  fi
  echo "${macaddr}"
}

if ((user_net)); then
  printf -v port "22%02d" $((RANDOM * 100 / 32767 ))
  echo "INFO: ${vm} SSH port: ${port}"
  args+=(-nic "user,model=virtio,hostfwd=tcp::${port}-:22")
else
  args+=(-nic "bridge,br=qvm0,model=virtio,mac=$(macaddr)")
fi

# Headless mode (-d option), as opposed to graphical QEMU display
if ((detach)); then
  args+=(
      -display none
      -daemonize
      -pidfile "${RUNTIME_DIR}/${vm}".pid
  )
fi

"${cmd[@]}" "${args[@]}"
