#!/bin/env bash
#+ Run DNS and DHCP servers on qvm0 interface.
#+ Usage: SCRIPT [-n] [-t] [-d] [-f] [up | down]
set -eu
SCRIPT="$(basename "$0")"
DIR="$(dirname "$0")"
source "${DIR}/libqvm.sh"

#+ Options:
#+ -h  Print this message
#+ -d  Dry run: print the command that would be executed
dry_run=0
#+ -t  Test: perform a syntax check on the configuration
test=0
#+ -c  Configuration file for dnsmasq
#+     Default: net/dnsmasq.conf in this repository
conf="${DIR}/net/dnsmasq.conf"
#+ -d  Debug mode
debug=0
#+ -f  Foreground execution of dnsmasq
fg=0

while getopts tndfhc: opt; do
  case "${opt}" in
    t)
      test=1 ;;
    n)
      # shellcheck disable=SC2312
      dry_run=1 ;;
    d)
      debug=1 ;;
    f)
      fg=1 ;;
    c)
      conf="${OPTARG}" ;;
    *)
      usage "${opt}" ;;
  esac
done
shift $((OPTIND - 1))

action="${1:-up}"
pid_file="${QVM_DIR:-/var/vms}/run/dnsmasq.pid"
pcap_file="${QVM_DIR:-/var/vms}/run/dnsmasq.pcap"

trap cleanup EXIT

cleanup() {
  ((fg | debug)) && rm -f "${pid_file}"
}

down() {
  local pid
  if ! [[ -f "${pid_file}" ]]; then
    echo "dnsmasq does not seem to be running"
    return
  fi
  pid="$(cat "${pid_file:-/dev/null}")"
  if ! run sudo kill "${pid}"; then
    >&2 echo "ERROR: Unable to stop dnsmasq (${pid}). Stale pid ?"
    exit 1
  fi
}

up() {
  declare -a args=(
    --conf-file="${conf}" "$@"
  )

  if ((test)); then
    args+=(--test)
  fi

  if ((debug)); then
    args+=(
      --no-daemon
      --dumpfile="${pcap_file}"
    )
  elif ((fg)); then
    args+=("--keep-in-foreground")
  else
    args+=(
      --pid-file="${pid_file}"
    )
  fi
  run sudo dnsmasq "${args[@]}"
}

case "${action}" in
  up|down) "${action}" ;;
  *) usage ;;
esac
