#!/bin/bash
#+ Bring Linux bridge named qvm0, with assigned subnet 10.42.0.1/24
#+ Optionally preallocate tap ports.
#+
#+ Adapted from: https://wiki.archlinux.org/title/QEMU/Advanced_networking
#+
#+ Usage: SCRIPT [-h] [-n] [-t N_PORTS]
set -eu
SCRIPT="$(basename "$0")"
DIR="$(dirname "$0")"

# shellcheck source-path=SCRIPTDIR
source "${DIR}/libqvm.sh"

#+ Options:
#+ -h  Print this message
#+ -n  Print the commands that would be executed
#+ -t N_PORTS  TAP ports to pre-allocate
declare -i nports=0
while getopts nht: opt; do
  case "${opt}" in
    n)
      dry_run=1
      ;;
    t)
      nports="${OPTARG}"
      ;;
    *)
      usage "${opt}"
      ;;
  esac
done
shift $((OPTIND - 1))

br_addr="10.42.0.1/24"
br_name="qvm0"
if ! ip link show "${br_name}" &>/dev/null; then
  run sudo ip link add name "${br_name}" type bridge
  run sudo ip addr add "${br_addr}" dev "${br_name}"
  run sudo ip link set dev "${br_name}" up
fi

declare -i n
declare port_name
for ((n = 0; n < nports; n++)); do
  printf -v port_name '%stap%d' "${br_name}" "${n}"
  if ! ip link show "${port_name}" &>/dev/null; then
    echo "Created TAP device ${port_name}, plugged into bridge ${br_name}"
    run sudo ip tuntap add mode tap "${port_name}" user "${USER}"
    run sudo ip link set dev "${port_name}" master "${br_name}"
    run sudo ip link set dev "${port_name}" up
  fi
done

teardown=0
if ((teardown)); then
  sudo ip addr del dev "${br_name}" "${br_addr}"
  sudo ip link set dev "${br_name}" down
  sudo ip link delete "${br_name}" type bridge
fi
