#!/bin/bash
#+ Build cloud-init datasource for VM
#+ Usage: SCRIPT [-h] [-u USER_DATA] VM
set -eu
SCRIPT="$(basename $0)"
DIR="$(dirname $0)"
source "${DIR}/libqvm.sh"

out_dir="${QVM_DIR}/localds"
user_data="${DIR}/user-data/cloud.yaml"
while getopts hu: opt; do
  case "${opt}" in
    u)
      user_data="${OPTARG}"
      ;;
    *)
      usage
      ;;
  esac
done
shift $((OPTIND - 1))

mnt_point="$(mktemp -d /tmp/qvm-localds-XXXX)"
trap "sudo umount ${mnt_point} || true" EXIT

create_img() {
  truncate --size 256K "${img}"
  mkfs.vfat -n CIDATA "${img}"
  sudo mount -t vfat "${img}" "${mnt_point}"
  sudo cp "${user_data}" "${mnt_point}/user-data" || return 1
  cat <<EOF | sudo tee "${mnt_point}/meta-data" >/dev/null
instance-id: qvm-${vm}
hostname: ${vm}
local-hostname: ${vm}
EOF
}

for vm in "$@"; do
  img="${QVM_DIR}/localds/${vm}.img"
  create_img || errexit "Unable to create image: ${img}"
  info "Created datasource: ${img}"
done
