#!/bin/sh
set -eu
qvm_dir="${QVM_DIR}"
ssh_private_key="${qvm_dir}/ssh/id_ed25519"
ssh_config="${qvm_dir}/ssh/config"
user=guest
host="${1:-cp}"

export TERM=xterm-256color
ssh -F "${ssh_config}" "${user}@${host}"
