#!/bin/sh
set -eu

usage() {
  echo "SSH into HOST (default: cp) as USER (default: guest)
Usage: $(basename $0) [-h] [-u USER] [HOST]
"
  exit "${1:-0}"
}

qvm_dir="${QVM_DIR}"
ssh_private_key="${qvm_dir}/ssh/id_ed25519"
ssh_config="${qvm_dir}/ssh/config"
user=guest

while getopts hu: opt; do
  case "${opt}" in
    u)
      user="${OPTARG}"
      ;;
    h)
      usage
      ;;
    \?)
      usage 1
      ;;
  esac
done
shift $((OPTIND - 1))
host="${1:-cp}.qvm0.lan"

export TERM=xterm-256color
ssh -F "${ssh_config}" "${user}@${host}"
